export const GET_TV_SHOW_BY_ID = 'GET_TV_SHOW_BY_ID';
export const GET_TV_SHOWS = 'GET_TV_SHOWS';
export const ASYNC_GET_TV_SHOWS = 'ASYNC_GET_TV_SHOWS';
export const ASYNC_GET_TV_SHOW_BY_ID = 'ASYNC_GET_TV_SHOW_BY_ID';